name: image-build-test
on: [push, pull_request]

env:
  BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x

permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: step-security/setup-qemu-action@8c4aef027ab2df56e08f597afe6dd8cd31cb84f5 # v3.7.0

      - name: Set up Docker Buildx
        uses: step-security/setup-buildx-action@c60a792b446ef83310733d5cd9d0c8d6870d043f # v3.12.0
      
      - name: Prepare version file
        run: ./hack/get_version.sh > .version

      - name: Build and push container image
        uses: step-security/docker-build-push-action@a8c3d08b23f8be6aeed43eb1a14ce6fe51284438 # v6.18.0
        with:
          context: .
          push: false
          platforms: ${{ env.BUILD_PLATFORMS }}
          file: ./cmd/Dockerfile
